import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { ThemeProvider } from 'src/components/theme-provider';
import { TRPCProvider } from 'src/components/trpc-provider';
import { Toaster } from 'src/components/ui/toaster';
import 'src/styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'CODAS Decision Support System',
  description: 'Generated by create next app',
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <TRPCProvider>
      <html lang='en' suppressHydrationWarning>
        <body className={inter.className}>
          <ThemeProvider
            attribute='class'
            defaultTheme='system'
            enableSystem
            disableTransitionOnChange
          >
            {children}
            <Toaster />
          </ThemeProvider>
        </body>
      </html>
    </TRPCProvider>
  );
}
