import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '~/styles/globals.css';
import { Toaster } from '~/components/ui/toaster';
import { TRPCProvider } from '~/components/providers/trpc-provider';
import { ThemeProvider } from '~/components/providers/theme-provider';

export const metadata: Metadata = {
  title: {
    template: '%s | CODAS Decision Support System',
    default: 'CODAS Decision Support System',
  },
  description: 'Generated by create next app',
  icons: './favicon.ico',
};

const inter = Inter({ subsets: ['latin'] });

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <TRPCProvider>
      <html lang='en' suppressHydrationWarning>
        <body className={inter.className}>
          <ThemeProvider
            attribute='class'
            defaultTheme='system'
            enableSystem
            disableTransitionOnChange
          >
            {children}
            <Toaster />
          </ThemeProvider>
        </body>
      </html>
    </TRPCProvider>
  );
}
